int backtrace_MAINNAME(HashTable *hashTable,int score,INT_INDICES) {
    // index_start

FOR_LOOP_NEW_VARIABLES_OPEN
CHILDREN_SUM
INDENT  if(score==CHILDREN_MAX){
CHILDREN_BACKTRACE
INDENT    return;
INDENT  }
FOR_LOOP_NEW_VARIABLES_CLOSE

}
